data_params:
  train_data_pkl_path: 'Data/deepcad_subset/train/*/solid*.pkl'
  val_data_pkl_path: 'Data/deepcad_subset/val/*/solid*.pkl'
  train_batch_size: 2
  val_batch_size: 1
  num_workers: 32
  max_faces: 10
  face_shuffle: True
  debug: True
  

model_params:
  in_channels: 1
  out_channels: 1
  solid_params:
    encode_params:
      types: ["EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D"]
      attns: [False, False, False]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [False]
    decode_params:
      types: ["DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeBlock3D"]
      attns: [False, False, False]
    cross_attn_scale: [1, 1, 1,   1,   1, 1, 1]
  face_params:
    encode_params:
      types: ["EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D"]
      attns: [True, True, False]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [True]
    decode_params:
      types: ["DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeBlock3D"]
      attns: [True, True, False]
    cross_attn_scale: [1, 1, 1,   1,   1, 1, 1]
  #block_channels: [64, 128, 256, 256, 128, 64, 64]
  block_channels: [32, 64, 128, 128, 64, 32, 32]
  layers_per_block: 2
  attention_head_dim: 8
  norm_num_groups: 32
  norm_eps: 1.e-5
  cross_attn_zero_init: False
  cross_pos_encoding_num: 0 # number of position encoding

trainer_params:
  manual_seed: 4488
  accelerator: 'gpu'
  max_epochs: 5000
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 50
  limit_val_batches: 1
  val_check_interval: 300
  num_sanity_val_steps: 1
  detect_anomaly: False
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  default_root_dir: 'sdf_diffusion/logs/raw'

exp_params:
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.99
  recon_loss_type: "l2" # l1 or l2
  diffusion_steps: 50
  only_valid_face: False
  latent_std_mean_path: 'reconstruction/logs/latent_dim_4_mean_std.pkl'
  face_diffusion_model:
    pretrained_path: null #'diffusion_transformer/logs/face_only/lightning_logs/version_0/checkpoints/last-model-epoch=59.ckpt'
  pretrained_model_path: null #'cond_diffusion_transformer/logs/cond_solid_allow_invalid_face_debug_20/lightning_logs/version_1/checkpoints/last-model-epoch=129.ckpt'


