data_params:
  train_batch_size: 100
  val_batch_size: 15
  num_workers: 32
  max_faces: 5
  face_shuffle: True
  debug: True
  debug_size: 1
  latent_size: 8

model_params:
  in_channels: 16
  out_channels: 16
  solid_params:
    encode_params:
      types: ["EncodeBlock3D", "EncodeBlock3D", "EncodeBlock3D"]
      attns: [False, True, True]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [True]
    decode_params:
      types: ["DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeBlock3D"]
      attns: [True, True, False]
    cross_attn_scale: [1, 1, 1,   1,   1, 1, 1]
  face_params:
    encode_params:
      #types: ["EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D", "EncodeBlock3D"]
      types: ["EncodeBlock3D", "EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D"]
      attns: [False, False, False, False]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [False]
    decode_params:
      types: ["DecodeBlock3D", "DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeBlock3D"]
      #types: ["DecodeBlock3D", "DecodeBlock3D", "DecodeBlock3D", "DecodeUpBlock3D"]
      attns: [False, False, False, False]
    #cross_attn_scale: [1, 1, 1,   1,   1, 1, 1]
    cross_attn_scale: [0, 0, 0,0,   0,  0,0, 0, 0]
  #block_channels: [64,  128, 128, 256, 256, 128, 128, 64, 64]
  #block_channels: [64, 128, 128, 128, 128, 64, 64]
  block_channels: [32, 64, 128, 128, 128, 128, 64, 32, 32]
  layers_per_block: 2
  attention_head_dim: 8
  norm_num_groups: 32
  norm_eps: 1.e-5
  cross_attn_zero_init: False
  cross_pos_encoding_num: 0 # number of position encoding
  has_solid_model: False
  has_s2f_model: False
  has_f2f_model: False
  has_f2s_model: False

trainer_params:
  manual_seed: 123
  accelerator: 'gpu'
  max_epochs: 5000
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 100
  limit_val_batches: 1
  val_check_interval: 2000
  num_sanity_val_steps: 1
  detect_anomaly: False
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  default_root_dir: 'sdf_diffusion/logs/random_check_sb'

exp_params:
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.9999
  loss_type: "l2" # l1 or l2
  diffusion_steps: 50
  face_model:
    config: 'vqvae/logs/vqvae_face_dist_codebook_dim_4/lightning_logs/version_1/config.yaml'
    pretrained_path: 'vqvae/logs/vqvae_face_dist_codebook_dim_4/lightning_logs/version_1/checkpoints/last-model-epoch=76.ckpt'
  sdf_model: 
    config: 'vqvae/logs/vqvae_voxel_sdf_codebook_dim_4/lightning_logs/version_1/config.yaml'
    pretrained_path: 'vqvae/logs/vqvae_voxel_sdf_codebook_dim_4/lightning_logs/version_1/checkpoints/last-model-epoch=76.ckpt'
  latent_std_mean_path: 'reconstruction/logs/latent_dim_4_mean_std.pkl'
  face_diffusion_model:
    pretrained_path: null #'diffusion_transformer/logs/face_only/lightning_logs/version_0/checkpoints/last-model-epoch=59.ckpt'
  pretrained_model_path: null #'sdf_diffusion/logs/latent_face_solid_full_20/lightning_logs/version_1/checkpoints/last-model-epoch=39.ckpt'
  generate_solid: False
