data_params:
  train_data_pkl_path: 'train_valid_data_list.pkl'
  val_data_pkl_path: 'val_valid_data_list.pkl'
  train_batch_size: 4
  val_batch_size: 2
  num_workers: 32
  max_faces: 10

model_params:
  n_channels: 11 # max_faces + 1

trainer_params:
  manual_seed: 44
  accelerator: 'cpu'
  max_epochs: 200
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 50
  limit_val_batches: 5
  val_check_interval: 1.0
  num_sanity_val_steps: 1
  detect_anomaly: False
  default_root_dir: 'diffusion/logs/vq_latent'

exp_params:
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.95
  recon_loss_type: "l2" # l1 or l2
  diffusion_steps: 50
  face_model: 
    config: 'vqvae/configs/vqvae_voxel_face_dist.yaml'
    pretrained_path: null
  sdf_model: 
    config: 'vqvae/configs/vqvae_voxel_sdf.yaml'
    pretrained_path: null
  pretrained_model_path: null #'vqvae/logs/vqvae_voxel_sdf_full_conv/lightning_logs/version_0/checkpoints/last.ckpt'


