data_params:
  train:
    faces_model_path: 'deepsdf/logs/faces/lightning_logs/version_1'
    solid_model_path: 'deepsdf/logs/solid/lightning_logs/version_0'
    batch_size: 128
    num_workers: 32
    faces_num: 30
    face_shuffle: True
  val:
    faces_model_path: 'deepsdf/faces/lightning_logs/version_1'
    solid_model_path: 'deepsdf/solid/lightning_logs/version_0'
    batch_size: 10
    num_workers: 32
    faces_num: 30
    face_shuffle: True

model_params:
  freq_shift: 0
  flip_sin_to_cos: True
  act_fn: 'silu'
  has_solid_model: True

trainer_params:
  manual_seed: 44
  accelerator: 'gpu'
  max_epochs: 50000
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 100
  limit_val_batches: 1
  val_check_interval: 20000
  num_sanity_val_steps: 1
  detect_anomaly: False
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  default_root_dir: 'deepsdf_diffusion/logs/face_solid'

exp_params:
  render_type: 'face_solid'
  prediction_type: 'sample' # epsilon or sample
  lr: 0.00005
  weight_decay: 0.0
  lr_decay: 0.999
  loss_type: "l2" # l1 or l2
  diffusion_steps: 250
  face_model:
    config: 'deepsdf/logs/faces/lightning_logs/version_1/config.yaml'
    pretrained_path: 'deepsdf/logs/faces/lightning_logs/version_1/checkpoints/last-*'
  solid_model: 
    config: 'deepsdf/logs/solid/lightning_logs/version_0/config.yaml'
    pretrained_path: 'deepsdf/logs/solid/lightning_logs/version_0/checkpoints/last-*'
  face_diffusion_model:
    pretrained_path: null #'diffusion_transformer/logs/face_only/lightning_logs/version_0/checkpoints/last-model-epoch=59.ckpt'
  pretrained_model_path: null #'sdf_diffusion/logs/latent_full_solid_cond/lightning_logs/version_2/checkpoints/last-model-epoch=436.ckpt'
  generate_solid: True
