data_params:
  train:
    data_path: 'Data/processed/deepcad_subset_v2/train' #'train_valid_data_list.pkl'
    data_key: 'face_bounded_distance_field'
    filter_data_path: null #'Data/processed/deepcad_subset/train_bad_list.pkl'
    clip_value: 0.1
    data_format: 'npz' # 'pkl'
  val:
    data_path: 'Data/processed/deepcad_subset_v2/val' # 'val_valid_data_list.pkl'
    data_key: 'face_bounded_distance_field'
    filter_data_path: null #'Data/processed/deepcad_subset/val_bad_list.pkl'
    clip_value: 0.1
    data_format: 'npz' # 'pkl'
  batch_size: 60
  num_workers: 32
  use_cache: False

model_params:
  n_channels: 1
  with_conv: True
  num_res_blocks: 2
  channels: [1,2,4,4] # downsample 3 time
  voxel_size: 64
  ch: 32
  codebook_dim: 4
  codebook_size: 8192

trainer_params:
  manual_seed: 44
  accelerator: 'gpu'
  max_epochs: 200
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 50
  limit_val_batches: 5
  val_check_interval: 1.0
  num_sanity_val_steps: 1
  detect_anomaly: False
  default_root_dir: 'vqvae2/logs/vqvae_face_npz'

exp_params:
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.95
  vq_weight: 0.25
  kld_weight: 0.00005 #0.0000005
  recon_loss_type: "l2" # l1 or l2
  pretrained_model_path: 'vqvae2/logs/vqvae_face_npz/lightning_logs/version_5/checkpoints/last-model-epoch=05.ckpt'
  phase: "face" # sdf or face

  
