data_params:
  debug: False
  class_type: LatentDataset #LatentDataset VoxelDataset
  train:
    data_path: 'vqvae/logs/recon/train_npz_v2/lightning_logs/version_0/pkl' #'Data/processed/deepcad_subset_v2/train/*'
    filter_data_path: 'Data/processed/deepcad_subset/train_bad_list.pkl'
    batch_size: 512
    num_workers: 16
    max_data_faces: 20
    max_faces: 1
    face_shuffle: True
    cache_size: 3000000
  val:
    data_path: 'vqvae/logs/recon/val_npz_v2/lightning_logs/version_0/pkl' #'Data/processed/deepcad_subset_v2/val/*'
    filter_data_path: 'Data/processed/deepcad_subset/val_bad_list.pkl'
    batch_size: 6
    num_workers: 16
    max_data_faces: 20
    max_faces: 1
    face_shuffle: True
    debug_size: 100000
    cache_size: 3000000

model_params:
  class_type: 'Solid3DModel_v2'
  in_channels: 4
  out_channels: 4
  solid_params:
    encode_params:
      types: ["EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D"]
      attns: [False, False, False, False]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [False]
    decode_params:
      types: ["DecodeBlock3D", "DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeUpBlock3D"]
      attns: [False, False, False, False]
  face_params:
    encode_params:
      types: ["EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeDownBlock3D", "EncodeBlock3D"]
      attns: [False, False, False, False]
    mid_params:
      types: ["EncodeBlock3D"]
      attns: [False]
    decode_params:
      types: ["DecodeBlock3D", "DecodeUpBlock3D", "DecodeUpBlock3D", "DecodeUpBlock3D"]
      attns: [False, False, False, False]
  cross_attn_params:
    zero_init: True
    encoding_num: 0 # number of position encoding
    f2f_model: [False, False, False, False,  False,  False, False, False, False]
    f2s_model: [False, False, False, True,   True,  False, False, False, False]
    s2f_model: [True, True, True, True,   True,   True, True, True, True]
    #f2f_model: [False, False, False, False,  True,  False, False, False, False]
    #f2s_model: [False, False, False, False,   True,  False, False, False, False]
    #s2f_model: [False, False, False, False,   True,   False, False, False, False]
    #f2f_model: [False, True, True, True,  True,  True, True, False, False]
    #f2s_model: [False, True, True, True,  True,  True, True, False, False]
    #s2f_model: [False, True, True, True,  True,  True, True, False, False]
  #block_channels: [32, 64, 128, 256, 256, 128, 64, 32, 32]
  block_channels: [64, 128, 256, 512, 512, 256, 128, 64, 64]
  layers_per_block: 2
  attention_head_dim: 8
  norm_num_groups: 32
  norm_eps: 1.e-5
  freq_shift: 0
  flip_sin_to_cos: True
  act_fn: 'silu'

trainer_params:
  manual_seed: 123456
  accelerator: 'gpu'
  max_epochs: 5000
  precision: 32
  num_nodes: 1
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 100
  limit_val_batches: 1
  val_check_interval: 3000
  num_sanity_val_steps: 1
  detect_anomaly: False
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  default_root_dir: 'solid_model/logs/solid_model'

exp_params:
  guidance_scale: 1.0
  render_type: 'face_solid'
  prediction_type: 'sample' # epsilon or sample
  lr: 0.0001
  freeze_modules: [] #['face_model', 'solid_model']
  weight_decay: 0.0
  lr_decay: 0.99
  loss_type: "l2" # l1 or l2
  diffusion_steps: 250
  visual_type: 'vanilla' # brep or vanilla 
  face_model:
    config: 'vqvae/logs/vqvae_face_npz/lightning_logs/version_0/config.yaml'
    pretrained_path: 'vqvae/logs/vqvae_face_npz/lightning_logs/version_0/checkpoints/last-model-epoch=21.ckpt'
  sdf_model: 
    config: 'vqvae/logs/vqvae_solid_npz/lightning_logs/version_0/config.yaml'
    pretrained_path: 'vqvae/logs/vqvae_solid_npz/lightning_logs/version_0/checkpoints/last-model-epoch=21.ckpt'
  latent_std_mean_path: 'vqvae/logs/recon/val_npz/lightning_logs/version_1/mean_std.pkl'
  pretrained_model_path: 'uncond_diffusion/logs/full_npz_pretrained/lightning_logs/version_20/checkpoints/last-model-epoch=02.ckpt'
  #'uncond_diffusion/logs/full_npz_no_cross_attn/lightning_logs/version_0/checkpoints/last-model-epoch=131.ckpt'
